### ISSUE TITLE
 round.go:271: round system:idle : Crash

### ISSUE THREAD

**Issue by DanTulovsky** [DanTulovsky/pepper-poker#1]
2020/11/21 08:33:36 manager.go:230: manager Processing user action: ActionGetInfo (opts: <nil>)
2020/11/21 08:33:36 manager.go:231: manager   > playerID: ff7199db-8557-4628-97db-d7f4e31b4910; tableID: 0c1e04fb-f797-4ef7-a858-c4378ff5ef92; roundID:
2020/11/21 08:33:37 round.go:589: round Player [[robot] Knightabalone] idle too long [5h0m0s], checking...
2020/11/21 08:33:37 round.go:271: round system:idle
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x152fdea]

goroutine 64 [running]:
github.com/DanTulovsky/pepper-poker/poker.(*PlayerInfo).Name(...)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/poker/player_info.go:78
github.com/DanTulovsky/pepper-poker/poker.(*Round).LogPlayerTurn(0xc0000a4340, 0x190044f, 0xb, 0xc000174480, 0x24, 0xc0024ba930, 0x24, 0xc000000001, 0x0)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/poker/round.go:361 +0x8a
github.com/DanTulovsky/pepper-poker/poker.(*Round).canAdvanceState(0xc0000a4340, 0x18e1b00)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/poker/round.go:591 +0x225
github.com/DanTulovsky/pepper-poker/poker.(*roundFlopState).Tick(0xc002bc2300, 0xc, 0x0)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/poker/state_05_roundFlop.go:62 +0x36c
github.com/DanTulovsky/pepper-poker/poker.(*Round).Tick(...)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/poker/round.go:531
github.com/DanTulovsky/pepper-poker/manager.(*gamePlayingState).Tick(0xc0004931c0, 0x0, 0x0)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/manager/state_04_gamePlaying.go:79 +0x5a
github.com/DanTulovsky/pepper-poker/manager.(*Table).Tick(...)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/manager/table.go:284
github.com/DanTulovsky/pepper-poker/manager.(*Manager).Run(0xc000202100, 0xc0000a2000, 0xc00031a240)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/manager/manager.go:87 +0x262
created by github.com/DanTulovsky/pepper-poker/server.RunServer
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker/server/server.go:101 +0x50e
exit status 2

**Comment by DanTulovsky** [comment]
obsolete
