### ISSUE TITLE
server crash when client sends invalid proto

### ISSUE THREAD

**Issue by DanTulovsky** [DanTulovsky/pepper-poker#2]
panic: interface conversion: interface {} is *proto.AckTokenResponse, not *proto.TakeTurnResponse

goroutine 102 [running]:
github.com/DanTulovsky/pepper-poker-v2/server/server.(*pokerServer).TakeTurn(0xc0004cae20, 0x1d69660, 0xc00030a3c0, 0xc0000c0c40, 0xc0004cae20, 0x8, 0x1c5e6ef)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker-v2/server/server/grpc_server.go:168 +0x327
github.com/DanTulovsky/pepper-poker-v2/proto._PokerServer_TakeTurn_Handler.func1(0x1d69660, 0xc00030a3c0, 0x1bd8940, 0xc0000c0c40, 0x1b, 0xc0003bef00, 0x1d69660, 0xc00030a3c0)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker-v2/proto/poker.pb.go:2389 +0xa2
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x1d69660, 0xc00030a3c0, 0x1bd8940, 0xc0000c0c40, 0xc000490c60, 0xc000490c80, 0xc0003854f0, 0x236d180, 0x0, 0xc000490ce0)
	/Users/dant/go/src/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:108 +0x105
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1d69660, 0xc00030a3c0, 0x1bd8940, 0xc0000c0c40, 0x1c55646, 0xd, 0x1c5e6dc, 0x1b)
	/Users/dant/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x87
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x1d69660, 0xc00030a000, 0x1bd8940, 0xc0000c0c40, 0xc000490c60, 0xc000490ca0, 0xc000490cd8, 0xc000490cc0, 0xc000490c60, 0xc000490cc0)
	/Users/dant/go/src/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing/server_interceptors.go:38 +0x243
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1d69660, 0xc00030a000, 0x1bd8940, 0xc0000c0c40, 0xc000359980, 0xc0001b8d80, 0x0, 0xc000490c80)
	/Users/dant/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x87
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1d69660, 0xc00030a000, 0x1bd8940, 0xc0000c0c40, 0xc000490c60, 0xc000490c80, 0xc000359980, 0xc0002e5930, 0x1050818, 0x30)
	/Users/dant/go/src/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x169
github.com/DanTulovsky/pepper-poker-v2/proto._PokerServer_TakeTurn_Handler(0x1ba99c0, 0xc0004cae20, 0x1d69660, 0xc00030a000, 0xc000359980, 0xc000251d10, 0x1d69660, 0xc00030a000, 0xc0004ae5a0, 0x8e)
	/Users/dant/go/src/github.com/DanTulovsky/pepper-poker-v2/proto/poker.pb.go:2391 +0x1de
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017f880, 0x1d715c0, 0xc00037b380, 0xc000496800, 0xc000251ec0, 0x232b3a8, 0x0, 0x0, 0x0)
	/Users/dant/go/src/google.golang.org/grpc/server.go:1210 +0xa63
google.golang.org/grpc.(*Server).handleStream(0xc00017f880, 0x1d715c0, 0xc00037b380, 0xc000496800, 0x0)
	/Users/dant/go/src/google.golang.org/grpc/server.go:1533 +0x1405
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00053e540, 0xc00017f880, 0x1d715c0, 0xc00037b380, 0xc000496800)
	/Users/dant/go/src/google.golang.org/grpc/server.go:871 +0xdd
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/dant/go/src/google.golang.org/grpc/server.go:869 +0x358

**Comment by DanTulovsky** [comment]
fixed by adding defer() calls to catch panics.  Really should get rid of these type assertions.
